# Generated by Django 4.0.5 on 2022-06-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='Email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='master',
            name='Name',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='master',
            name='Password',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
