# Generated by Django 4.0.5 on 2022-06-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0002_master_email_master_name_master_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='Name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='master',
            name='Password',
            field=models.CharField(max_length=25),
        ),
    ]
