# Generated by Django 4.0.5 on 2022-07-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0003_alter_master_email_alter_master_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delete', models.CharField(max_length=25)),
            ],
        ),
    ]
