# Generated by Django 4.0.5 on 2022-07-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0004_delete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delete',
        ),
    ]
