# Generated by Django 4.0.5 on 2022-07-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0005_delete_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='chkboxcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=50)),
            ],
        ),
    ]
