# Generated by Django 4.0.5 on 2022-07-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0007_status_master_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='Status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
