# Generated by Django 4.0.5 on 2022-07-17 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0008_remove_master_status_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='Status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='demoApp.status'),
            preserve_default=False,
        ),
    ]
