# Generated by Django 4.0.5 on 2022-07-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0009_status_master_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='Status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='demoApp.status'),
        ),
    ]
